[build]
builder = "nixpacks"

[deploy]
startCommand = "docker-compose up -d"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[services.postgres]
dockerfile = false

[services.backend]
dockerfile = false

[services.frontend]
dockerfile = false

[services.prometheus]
dockerfile = false

[services.grafana]
dockerfile = false
